easy_admin:
   entities:
       User:
           class: App\Entity\User
#           list:
#               fields: ['username', 'email', 'is_active']
       Exhibit:
           class: App\Entity\Exhibit
       Party:
           class: App\Entity\Party
       Weekend:
           class: App\Entity\Weekend