security:
    providers:
        our_db_provider:
            entity:
                class: App\Entity\User

    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        App\Entity\User:
            algorithm: bcrypt
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: true
            form_login:
               login_path: login
               check_path: login
            logout:
                path: /logout
                target: /
            pattern:    ^/
            http_basic: ~
            provider: our_db_provider

    access_control:
        - { path: ^/profil, roles: ROLE_USER }
        - { path: ^/admin, roles: ROLE_ADMIN }
#        - { path: ^/profile, roles: ROLE_USER }